### ISSUE TITLE
Fix constant requests to POLLOUT

### ISSUE THREAD

**Issue by mrizhakov** [andreasmaucher/webserv#12]
main loop stays all the time in the state of ready to write to socket(unless receiving a request).
Manually switch from POLLIN to POLLOUT once a request is processed and back after response is ready to send out

**Comment by cariestevez** [comment]
Done! I am switching back to POLLIN after sending the response + added conditions for closing the connection when the response is an error status code or the client specified it in the request. I also created an closeConnection function and slightly modified the logic for it to work seemless.
All the test requests I'm sending from postman are being successfull :D

**Comment by cariestevez** [comment]
Done! I am switching back to POLLIN after sending the response + added conditions for closing the connection when the response is an error status code or the client specified it in the request. I also created an closeConnection function and slightly modified the logic for it to work seemless.
All the test requests I'm sending from postman are being successfull :D
